import assert from 'node:assert/strict';import fs from 'node:fs';import crypto from 'node:crypto';
import {addPokemon} from '../dist/additions.mjs';import {inspectRoster,editRoster} from '../dist/roster.mjs';import {MON_INDEX,TEMPLATE_SHA256} from '../dist/mon-index.mjs';import {NATURES,readFields} from '../dist/mon-fields.mjs';import {parseSave} from '../dist/core.mjs';
const input=new Uint8Array(fs.readFileSync(process.argv[2])),templates=new Uint8Array(fs.readFileSync(new URL('../dist/mon-templates.bin',import.meta.url)));assert.equal(crypto.createHash('sha256').update(templates).digest('hex'),TEMPLATE_SHA256);assert.equal(templates.length,MON_INDEX.filter(m=>!m.unavailable).length*7600);assert.equal(MON_INDEX.filter(m=>m.unavailable).length,4);
const ids=[1502,1553,1809,1739,1955];const requests=ids.map((species,i)=>({species,level:50,destination:i<2?'party':'pc',box:2,slot:18+i}));const added=addPokemon(input,requests,templates),r=inspectRoster(added);const mons=[r.party[0],r.party[1],r.party[2],r.boxes[2][20],r.boxes[2][21],r.boxes[2][22]];assert.deepEqual(mons.slice(1).map(m=>m.mapped),ids);
const changes=mons.map((m,i)=>({key:m.key,destination:m.destination,box:m.box,slot:m.slot,nickname:'FORM'+i,nature:i===0?0:15,gender:m.genderChoices.includes('female')?'female':m.gender,abilitySlot:m.abilities.at(-1).slot,heldItem:410,moves:[85,53,94,0],ev:[4,0,0,252,252,0]}));const edited=editRoster(added,changes),out=inspectRoster(edited);const result=changes.map(c=>c.destination==='party'?out.party[c.slot]:out.boxes[c.box][c.slot]);
for(let i=0;i<result.length;i++){const a=mons[i],b=result[i],c=changes[i];for(const k of ['nickname','nature','gender','abilitySlot','heldItem'])assert.equal(b[k],c[k],k);assert.deepEqual(b.moves,c.moves);assert.deepEqual(b.ev,c.ev);assert.equal(a.mapped,b.mapped);const v=x=>new DataView(x.raw.buffer,x.raw.byteOffset).getUint32(0,true),xor=n=>(n>>>16)^(n&65535);assert.equal(xor(v(a)),xor(v(b)),'preserve shiny XOR');}
const before=new Uint8Array(added),s=parseSave(added);assert.deepEqual(added,before);assert.deepEqual(edited.slice(0,14*4096),added.slice(0,14*4096));assert.deepEqual(edited.slice(28*4096),added.slice(28*4096));
assert.throws(()=>editRoster(added,[{...changes[0],moves:[0,0,0,0]}]));assert.throws(()=>editRoster(added,[{...changes[0],moves:[85,85,0,0]}]));assert.throws(()=>editRoster(added,[{...changes[0],abilitySlot:3}]));assert.throws(()=>editRoster(added,[{...changes[0],heldItem:455}]));assert.throws(()=>editRoster(added,[{...changes[0],nature:25}]));assert.throws(()=>addPokemon(input,[{species:1805,level:5,destination:'party'}],templates));
const onlyName=editRoster(added,[{key:mons[0].key,destination:'party',slot:0,nickname:'TEST'}]);const p=s.world+0x238;assert.deepEqual(onlyName.slice(p+20,p+76),added.slice(p+20,p+76));assert.deepEqual(onlyName.slice(p,p+8),added.slice(p,p+8));
fs.writeFileSync('/workspace/scratch/e40f1f76aae3/fields-test-only.sav',edited);fs.writeFileSync('/workspace/scratch/e40f1f76aae3/fields-expectations.json',JSON.stringify(result.map(m=>({destination:m.destination,slot:m.slot,box:m.box,mapped:m.mapped,nature:m.nature,gender:m.gender,ability:m.abilities.find(a=>a.slot===m.abilitySlot).id,heldItem:m.heldItem,moves:m.moves,ev:m.ev,stats:m.stats,nickname:m.nickname}))));
console.log('PASS:',MON_INDEX.length,'catalog entries;',MON_INDEX.filter(m=>!m.unavailable).length,'templates. Mega/Alola/Hisui/other forms, name, all field layouts, nature Hardy, gender/shiny preservation, ability, held item, moves/EV, invalid values, name-only preservation.');
