import assert from 'node:assert/strict';import fs from 'node:fs';
import {parseSave,PROFILE} from '../dist/core.mjs';import {addPokemon,readStorage} from '../dist/additions.mjs';import {inspectRoster,editRoster,evForStat,calculateStats,describeMon} from '../dist/roster.mjs';import {STAT_DATA as D} from '../dist/stat-data.mjs';
const input=new Uint8Array(fs.readFileSync(process.argv[2])),templates=new Uint8Array(fs.readFileSync(new URL('../dist/mon-templates.bin',import.meta.url))),before=input.slice();
const added=addPokemon(input,[{destination:'party',species:150,level:50},{destination:'pc',box:2,slot:18,species:384,level:100},{destination:'pc',box:20,slot:29,species:25,level:5}],templates);
const roster=inspectRoster(added);assert.equal(roster.party.length,6);assert.equal(roster.boxes.length,21);assert.equal(roster.boxes[2][18].species,384);assert.equal(roster.boxes[2][0],null);assert.equal(roster.boxes[20][29].species,25);assert.throws(()=>addPokemon(added,[{destination:'pc',box:2,slot:18,species:25,level:5}],templates));assert.throws(()=>addPokemon(input,[{destination:'pc',box:0,slot:30,species:25,level:5}],templates));
const requests=[roster.party[0],roster.party[1],roster.boxes[2][18],roster.boxes[20][29]].map(m=>({...m,ev:[252,252,4,0,0,0]}));const output=editRoster(added,requests),after=inspectRoster(output);requests.forEach(m=>assert.deepEqual((m.destination==='party'?after.party[m.slot]:after.boxes[m.box][m.slot]).ev,m.ev));const s=parseSave(added),allowed=new Set();for(const m of requests){if(m.destination==='party'){for(const k of [32,33,34,35,36,37,...Array.from({length:14},(_,i)=>62+i)])allowed.add(s.world+0x238+m.slot*76+k);}else{for(let k=32;k<38;k++){let p=4+(m.box*30+m.slot)*52+k;for(let id=5;id<=13;id++){if(p<PROFILE.sizes[id]){allowed.add(s.active.sections.get(id)+p);break}p-=PROFILE.sizes[id]}}}}for(const id of [1,5,6,7,8,9,10,11,12,13])for(const k of [0xff6,0xff7])allowed.add(s.active.sections.get(id)+k);for(let i=0;i<added.length;i++)if(added[i]!==output[i])assert.ok(allowed.has(i),'Unexpected write '+i);
assert.deepEqual(input,before);assert.deepEqual(readStorage(added).slice(32764),readStorage(output).slice(32764));for(const ev of [[253,0,0,0,0,0],[252,252,252,0,0,0],[-1,0,0,0,0,0],[1.5,0,0,0,0,0]])assert.throws(()=>editRoster(added,[{...requests[0],ev}]));assert.deepEqual(editRoster(added,[]),added);
const m=roster.party[0],ev=[0,252,0,0,0,0],target=calculateStats(m,ev,roster.ctx)[1],resolved=evForStat(m,m.ev,roster.ctx,1,target);assert.equal(calculateStats(m,resolved,roster.ctx)[1],target);assert.throws(()=>evForStat(m,m.ev,roster.ctx,1,9999));
if(process.argv[3]){const fixtures=JSON.parse(fs.readFileSync(process.argv[3]));for(const c of fixtures){const mon=describeMon(new Uint8Array(c.raw),{destination:'party',slot:0},{flag:()=>false,bonus:c.bonus,capEnabled:true,cap:D.caps[0][38]+D.caps[0][95]});assert.deepEqual(mon.stats,c.stats)}console.log('PASS native-ROM fixtures:',fixtures.length)}
fs.writeFileSync('/workspace/scratch/e40f1f76aae3/roster-test-only.sav',output);fs.writeFileSync('/workspace/scratch/e40f1f76aae3/roster-expectations.json',JSON.stringify(requests.map(m=>{const result=m.destination==='party'?after.party[m.slot]:after.boxes[m.box][m.slot];return {destination:m.destination,box:m.box,slot:m.slot,ev:m.ev,stats:result.stats}})));
console.log('PASS 6 Party + 21x30 PC, exact vacant slot, occupied-slot rejection, EV limits, stat target, readback, cross-sector record, original/metadata preservation, byte write boundaries.');
